#####################
### BASE PACKAGES ###
#####################

# A faster drop in replacement for bin/magento cache:clean with file watcher
mage-os/magento-cache-clean

# The Admin Activity extension makes it easy to track all admin activity with comprehensive audit logging
mage-os/module-admin-activity-log

# Automatic AI content translation for Mage-OS
mage-os/module-automatic-translation

# Add a grid with the list of inventory reservations
mage-os/module-inventory-reservations-grid

# NoIndex NoFollow NoArchive Tag extension
mage-os/module-meta-robots-tag

# PageBuilder template import/export module
mage-os/module-page-builder-template-import-export

# PageBuilder cms widget module
mage-os/module-page-builder-widget

# Return Merchandise Authorization
mage-os/module-rma

# Mage-OS Theme Adminhtml Switcher
mage-os/module-theme-adminhtml-switcher

# Page transitions and speculative loading rules for Magento
mage-os/module-theme-optimization

# M137 Admin Theme
mage-os/theme-adminhtml-m137

############################
### IT SPECIFIC PACKAGES ###
############################

# TODO
